feature:
  name: feature
  description: A new feature not previously implemented
  position: 1
  enum: category

bug:
  name: bug
  description: A defect in the system that was not intended in the original design
  position: 2
  enum: category

change:
  name: change
  description: A change in behaviour from the original design
  position: 3
  enum: category

now:
  name: now
  description: Needs to be completed in the current release
  position: 1
  enum: when

soon:
  name: soon
  description: If there is time complete in the current release
  position: 2
  enum: when

later:
  name: later
  description: Will be scheduled in a future release
  position: 3
  enum: when

one:
  name: small
  description: This is a simple task
  position:  1
  enum: effort

two:
  name: medium
  description: This is task of moderate complexity
  position:  2
  enum: effort

four:
  name: large
  description: This task is either complex or time consuming
  position:  3
  enum: effort

eight:
  name: too large
  description: This task is very large and may need spliting
  position:  4
  enum: effort

customer:
  name: customer
  description: Can create and edit tasks. Specifically, they can enter a name, detail, set a category, mark it as related and set when either soon or later
  position:  1
  enum: access_level

developer:
  name: developer
  description: As well as do everything a customer can do, developers can assign, start, complete and set the effort of a task
  position:  2
  enum: access_level

