# mysql -u root -p
# grant all on *.* to 'velocity'@'localhost' identified by 'velocity';
# exit

common: &common
  adapter: mysql2
  username: velocity
  password: velocity
  host: localhost
  encoding: utf8
<% if File.exist? "/var/run/mysqld/mysqld.sock" %>
  socket: /var/run/mysqld/mysqld.sock
<% elsif File.exist? "/opt/local/var/run/mysql5/mysqld.sock" %>
  socket: /opt/local/var/run/mysql5/mysqld.sock
<% elsif File.exist? "/tmp/mysql.sock" %>
  socket: /tmp/mysql.sock
<% end %>

development:
  <<: *common
  database: velocity_development

test: &TEST
  <<: *common
  database: velocity_test

cucumber:
  <<: *TEST

production:
  <<: *common
  database: todo

