id:
  prefix: "#"

name:
  hint: "what's this about?"

author_id:
  prefix: "by "

assigned_id:
  prefix: "assigned: "
  prompt: unassign
  nil: (no one)

started_on:
  prefix: "started "
  suffix: " ago"

completed_on:
  prefix: "completed "
  suffix: " ago"

bug:
  label: bug?

effort_id:
  prompt: effort?
  nil: (effort)

related_id:
  prompt: relates to?
  nil: (not related)

save:
  hint: Save

