id:
  prefix: 'Task '

name:
  hint: "what's this about?"

detail:
  hint: would you like to expand on that?

author_id:
  prefix: "by "

category_id:
  prompt: type?

when_id:
  prefix: "for "
  prompt: when?

effort_id:
  prompt: effort?
  nil: (effort)

assigned_id:
  prefix: "assigned to "
  prompt: unassign
  nil: (no one)

started:
  prefix: "started "
  suffix: " ago"

completed_on:
  prefix: "completed "
  suffix: " ago"

related_id:
  prompt: relates to?
  nil: (not related)

save:
  hint: Save

